/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import battlemonsters.MetodosCrearBD;
import battlemonsters.MetodosUsuario;

/**
 *
 * @author Diego
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    private static int partida;
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarBotones();
    }
    
    private void cargarBotones(){
        partida1.setText("Jugador 1: " + MetodosUsuario.nombre(1));
        partida2.setText("Jugador 2: " + MetodosUsuario.nombre(2));
        partida3.setText("Jugador 3: " + MetodosUsuario.nombre(3));
        for(int i = 1; i<=3; i++){
            if(MetodosUsuario.nombre(i)==null)
                switch(i){
                    case 1: partida1.setText("Sin jugador");
                            break;
                    case 2: partida2.setText("Sin Jugador");
                            break;
                    case 3: partida3.setText("Sin Jugador");
                            break;
                }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        partida1 = new javax.swing.JButton();
        partida2 = new javax.swing.JButton();
        partida3 = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(255, 0, 0));
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("x");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, -1, -1));

        partida1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, java.awt.Color.black, java.awt.Color.lightGray));
        partida1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        partida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partida1ActionPerformed(evt);
            }
        });
        getContentPane().add(partida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 480, 80));

        partida2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, java.awt.Color.black, java.awt.Color.lightGray));
        partida2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        partida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partida2ActionPerformed(evt);
            }
        });
        getContentPane().add(partida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 480, 80));

        partida3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, java.awt.Color.black, java.awt.Color.lightGray));
        partida3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        partida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partida3ActionPerformed(evt);
            }
        });
        getContentPane().add(partida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 480, 80));

        nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuBackgroung.jpg"))); // NOI18N
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        MetodosCrearBD.desconectar();
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void partida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partida1ActionPerformed
        partida = 1;
        new NewGame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_partida1ActionPerformed

    private void partida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partida2ActionPerformed
        partida = 2;
        new NewGame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_partida2ActionPerformed

    private void partida3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partida3ActionPerformed
        partida = 3;
        new NewGame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_partida3ActionPerformed

    public static int getPartida(){
        return partida;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nombre;
    private javax.swing.JButton partida1;
    private javax.swing.JButton partida2;
    private javax.swing.JButton partida3;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
