/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Diego
 */
public class NewGame extends javax.swing.JFrame {

    /**
     * Creates new form NewGame
     */
    public NewGame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        continuar = new javax.swing.JButton();
        nuevaPartida = new javax.swing.JButton();
        foto = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        victorias = new javax.swing.JLabel();
        derrotas = new javax.swing.JLabel();
        textoNG = new javax.swing.JLabel();
        codPartidaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        continuar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        continuar.setText("Continuar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });
        getContentPane().add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 240, 70));

        nuevaPartida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nuevaPartida.setText("Nueva partida");
        nuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(nuevaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 240, 70));

        foto.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 390));

        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 240, 40));

        victorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        victorias.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(victorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 240, 40));

        derrotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        derrotas.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(derrotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 240, 40));

        textoNG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNG.setText("(Se borrarán los datos actuales)");
        getContentPane().add(textoNG, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 240, 40));

        codPartidaLabel.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(codPartidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        new SelectOption().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_continuarActionPerformed

    private void nuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaPartidaActionPerformed
        new NewPlayer().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nuevaPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel codPartidaLabel;
    private javax.swing.JButton continuar;
    public static javax.swing.JLabel derrotas;
    public static javax.swing.JLabel foto;
    public static javax.swing.JLabel nombre;
    private javax.swing.JButton nuevaPartida;
    private javax.swing.JLabel textoNG;
    public static javax.swing.JLabel victorias;
    // End of variables declaration//GEN-END:variables
}
